### ISSUE TITLE
Condition has length > 1 and only the first element will be used

### ISSUE THREAD

**Issue by ellessenne** [swihart/rmutil#9]
Hi,
I have been playing around with the `int` function and realised that there's a logical statement that causes the _"Condition has length > 1 and only the first element will be used"_ warning; actually, I have the following lines in my .Renviron file and it triggered errors:

```
_R_CHECK_LENGTH_1_CONDITION_=verbose
_R_CHECK_LENGTH_1_LOGIC2_=verbose
```

Reprex with my current .Renviron:

``` r
library(rmutil)
#> 
#> Attaching package: 'rmutil'
#> The following object is masked from 'package:stats':
#> 
#>     nobs
#> The following objects are masked from 'package:base':
#> 
#>     as.data.frame, units
rmutil::int(f = function(x) dnorm(x), a = 0, b = c(2, 3))
#> Error in if (b == Inf) {: the condition has length > 1
rmutil::int(f = function(x) dnorm(x), a = -c(2, 3), b = 0)
#> Error in if (b == Inf) {: the condition has length > 1
```

<sup>Created on 2020-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Reprex with a clean (empty) .Renviron:

``` r
library(rmutil)
#> 
#> Attaching package: 'rmutil'
#> The following object is masked from 'package:stats':
#> 
#>     nobs
#> The following objects are masked from 'package:base':
#> 
#>     as.data.frame, units
rmutil::int(f = function(x) dnorm(x), a = 0, b = c(2, 3))
#> Warning in if (b == Inf) {: the condition has length > 1 and only the first
#> element will be used
#> [1] 0.4772499 0.4986501
rmutil::int(f = function(x) dnorm(x), a = -c(2, 3), b = 0)
#> Warning in if (b == Inf) {: the condition has length > 1 and only the first
#> element will be used
#> [1] 0.4772499 0.4986501
```

<sup>Created on 2020-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think the issue might be here:
https://github.com/swihart/rmutil/blob/52a827da4090bc774485bbb5565dbd4295e4d6b8/R/int.r#L91

But there could be a similar issue for TOMS614 integration (I haven't checked, I just did a quick search in `int.r`):

https://github.com/swihart/rmutil/blob/52a827da4090bc774485bbb5565dbd4295e4d6b8/R/int.r#L132

Anything I can do for this? I am not sure about the algorithm used there and when/if to replace the single check with `any` or `all`.

**Comment by swihart** [comment]
Huh.  I thought I fixed these ( "Condition has length > 1 and only the first element will be used" warnings) for R version 4.0.0 but sure enough I just ran your reprex and got the same warnings.  I'll look into this in the next few days, starting with your suggestions.  Thanks!

**Comment by ellessenne** [comment]
Thanks @swihart! I think it should similar to the other fixes (but I haven't looked much into it), might just be some leftover code?

**Comment by swihart** [comment]
Started digging into this tonight.  Sure enough, on [May 25th, 2018](https://github.com/swihart/rmutil/commit/32b0317281d657a59d1920fd56046f0e6aed29f4) I changed line 218 of int.R but not line 91 or 132…

So we change those for v1.1.5 and get a clean run of the reprex:

````
> rmutil::int(f = function(x) dnorm(x), a = 0, b = c(2, 3))
[1] 0.4772499 0.4986501
> rmutil::int(f = function(x) dnorm(x), a = -c(2, 3), b = 0)
[1] 0.4772499 0.4986501

````

**Comment by ellessenne** [comment]
Awesome, thanks very much @swihart!
